### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by psills2410** [TheAlphamerc/country_provider#10]
I issue the following call in my Flutter dart program:

await CountryProvider.getAllCountries();

I get:

E/flutter (17082): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter (17082): 	CERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:359))

**Comment by psills2410** [comment]
I should add that this was working earlier today and I haven't (knowingly) made any certificate changes on my end.

**Comment by psills2410** [comment]
I just tried accessing https://restcountries.eu using Chrome. It reported:

NET::ERR_CERT_COMMON_NAME_INVALID

This server could not prove that it is restcountries.eu; its security certificate is from shortener.secureserver.net. This may be caused by a misconfiguration

**Comment by psills2410** [comment]
Now, going to https://restcountries.eu automatically redirects you to countrylayer.com. As of right now, that site is down, but earlier it was available. countrylayer.com appears to be providing exactly the same information as restcountries.eu used to. restcountries.eu  used to provide the information for free. countrylayer.com does have a free option and also several layers of paid options. All of these (free and paid) options are usage dependent. I don't know how (or even if) it is possible or practicable to amend country_provider to use countrylayer.com instead of restcountries.eu.

**Comment by Akeel1994** [comment]
I have the exact same issue

**Comment by TheAlphamerc** [comment]
> Now, going to https://restcountries.eu automatically redirects you to countrylayer.com. As of right now, that site is down, but earlier it was available. countrylayer.com appears to be providing exactly the same information as restcountries.eu used to. restcountries.eu used to provide the information for free. countrylayer.com does have a free option and also several layers of paid options. All of these (free and paid) options are usage dependent. I don't know how (or even if) it is possible or practicable to amend country_provider to use countrylayer.com instead of restcountries.eu.

It is possible to replace country_provider with countrylayer.com but that would work with a paid option better because in their free plan only 100 calls are allowed.

**Comment by TheAlphamerc** [comment]
This package is just a wrapper around  https://restcountries.eu and now the free unlimited APIs are down permanently so I am thinking of marking this package as discontinued.

**Comment by psills2410** [comment]
Thank you for responding. It's a shame that it looks like you will have to discontinue this package, especially as it was put up as recently as May.
